name: x509csr
description: Create X.509 Certificate Signing Requests
version: 1.0.0
homepage: https://www.davidjanes.com
author: David Janes <davidjanes@davidjanes.com

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ## asn1lib: ^0.5.5
  asn1lib: 
    path: /Users/david/consensas/asn1lib
  pointycastle: 1.0.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
